# Battery power report interval in seconds
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# Used to solve battery report-related errors in Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
# Report both sides battery via bluetooth
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Increase keyboard debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Increase the BLE radio transmit power of the keyboard to solve latency and poor left/right communication issues
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Change the default keyboard display name
CONFIG_ZMK_KEYBOARD_NAME="Corne"

# OLED related configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
# Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
# Bongo Cat animation
#CONFIG_ZMK_WIDGET_BONGO_CAT=y
CONFIG_NICE_OLED_GEM_ANIMATION=n

# Sleep related configuration
# Milliseconds of inactivity before entering idle state (5 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=300000
# Enable deep sleep support
CONFIG_ZMK_SLEEP=n
# Milliseconds of inactivity before entering deep sleep (60 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# ZMK Studio related configuration
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB related configuration
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n

# Enable mouse controls
CONFIG_ZMK_POINTING=y
